
#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_AT32_PWM_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_AT32_PWM_H_
#define AT32_PWM_COMPLEMENTARY	(1U << 8)

#define PWM_AT32_COMPLEMENTARY	(1U << 8)

/** @cond INTERNAL_HIDDEN */
#define AT32_PWM_COMPLEMENTARY_MASK	0x100
/** @endcond */
/** @} */

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_PWM_AT32_H_ */
